name: Glitch Sync

# Glitch Project: https://glitch.com/edit/#!/github-action
on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Buid
        run: npm run build
      - name: Sync to Glitch Project
        uses: kanadgupta/glitch-sync@main
        with:
          auth-token: '${{ secrets.authToken }}'
          project-id: '${{ secrets.projectId }}'
          path: build
