name: Glitch Sync

# Glitch Project: https://glitch.com/edit/#!/github-action
on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install Dependencies
        run: npm install
      - name: Buid
        run: npm run build

      - name: Deploy Hook 📦
        uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: '${{ secrets.deployHook }}'
